export enum EnumInfoType {
	ABOUT = 'ABOUT',
	HELP = 'HELP',
	FEEDBACK = 'FEEDBACK',
	PRIVACY_POLICY = 'PRIVACY_POLICY',
	RULE_OF_TRAVELLER = 'RULE_OF_TRAVELLER',
	USER_AGREEMENT = 'USER_AGREEMENT',
}
